- name: Installation Apache Server
  hosts: ubuntu
  become: yes

  tasks:
    - name: Installation apache2
      apt:
        name: apache2
        state: present
    - name: Activation service apache2
      service:
        name: apache2
        state: started 
    - na
