- name: manage httpd.conf
  hosts: centos
  become: yes
#  gather_facts: no


  tasks:
    - name: Installation httpd
      yum:
        name: httpd
        state: latest
    - name: "Copy Apache configuration file"
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/
      notify: 
        - restart_apache
  handlers:
        - name: restart_apache
          service:
            name: httpd
            state: restarted

