- name: haproxy
  hosts: centos
  gather_facts: yes
  become: yes
  
  vars:
    haproxy_backend_servers:
      - name: app1
        address: 192.168.0.1:80
      - name: app2
        address: 192.168.0.2:80
  roles:
    - ~/.ansible/roles/geerlingguy
#  when: (inventory_hostname == "node1")
    
