- name: Version .... 
  hosts: all
  become: yes
#  gather_facts: no
  

  tasks:
    - name: Version ...
      debug:
        msg: "{{ ansible_hostname }} utilise la distribution Redhat 8"
      when: ansible_distribution_major_version == "8"
