- name: "Utilisation des handlers"
  hosts: centos
  become: yes
  

  tasks:
    - name: "Copie du fichier httpd.conf vers les nodes"
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      notify: restart_httpd
  
  handlers:
    - name: "restart_httpd"
      service: 
        name: httpd
        state: restarted      

