- name: "Loop .... "
  hosts: centos
  become: yes
#  gather_facts: no

  vars_files:
    - packages.yml
    - groupes.yml
    - users.yml
  tasks:
    - name: "Installation des packages "
      yum:
        name: "{{ item }}"
        state: present
    - debug:
        msg: "Installation de {{ item }}"
      loop: "{{ package }}"

    - name: "Ajout des groupes"
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ groupes }}"

    - name: "Ajout de users"
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
