- name: Add Snort rule
  hosts: snort
  become: yes

  roles:
    - name: "ansible_security.ids_rule"
  vars:
    ids_provider: snort
    ids_rule: 'alert tcp any any -> any any (msg:"Attempted /etc/passwd Attack";
uricontent:"/etc/passwd"; classtype:attempted-user; sid:99000004; priority:1; rev:1;)'
    ids_rules_file: '/etc/snort/rules/local.rules'
    ids_rule_state: present
  tasks:    
  - name: import ids_rule_facts
    include_role:
      name: 'ansible_security.ids_rule_facts'
    vars:
      ids_rule_facts_filter: 'uricontent:"/etc/passwd"'
  - name: output rule facts
    debug:
      var: ansible_facts.ids_rules
